
[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
fyrox = "0.31.0"
wasm-bindgen = "0.2.87"
js-sys = "0.3.64"
web-sys = {version = "0.3.64", features = ['Document', 'Element', 'HtmlElement', 'Node', 'Window', 'Storage']}
